import { MapRoom, MapVent, PlayerColor, PlayerColorId, SecurityCamera, TaskType } from '../types';

export const PLAYER_COLORS: Record<PlayerColorId, PlayerColor> = {
  coral: {
    id: 'coral',
    name: 'Coral Rose',
    primary: '#E16162',
    shadow: '#B84546',
    visor: '#A5F3FC',
    badgeBg: '#FEE2E2',
    badgeText: '#991B1B',
    symbol: '▲',
    symbolName: 'Triangle',
  },
  mint: {
    id: 'mint',
    name: 'Alpine Mint',
    primary: '#10B981',
    shadow: '#047857',
    visor: '#CFFAFE',
    badgeBg: '#D1FAE5',
    badgeText: '#065F46',
    symbol: '■',
    symbolName: 'Square',
  },
  sky: {
    id: 'sky',
    name: 'Sky Blue',
    primary: '#38BDF8',
    shadow: '#0284C7',
    visor: '#E0F2FE',
    badgeBg: '#E0F2FE',
    badgeText: '#0369A1',
    symbol: '●',
    symbolName: 'Circle',
  },
  butter: {
    id: 'butter',
    name: 'Buttercup',
    primary: '#FBBF24',
    shadow: '#D97706',
    visor: '#E0F2FE',
    badgeBg: '#FEF3C7',
    badgeText: '#92400E',
    symbol: '★',
    symbolName: 'Star',
  },
  lavender: {
    id: 'lavender',
    name: 'Lavender',
    primary: '#A78BFA',
    shadow: '#7C3AED',
    visor: '#EDE9FE',
    badgeBg: '#EDE9FE',
    badgeText: '#5B21B6',
    symbol: '◆',
    symbolName: 'Diamond',
  },
  rosewood: {
    id: 'rosewood',
    name: 'Terracotta',
    primary: '#FB7185',
    shadow: '#E11D48',
    visor: '#FFE4E6',
    badgeBg: '#FFE4E6',
    badgeText: '#9F1239',
    symbol: '✚',
    symbolName: 'Cross',
  },
  cerulean: {
    id: 'cerulean',
    name: 'Deep Cobalt',
    primary: '#3B82F6',
    shadow: '#1D4ED8',
    visor: '#DBEAFE',
    badgeBg: '#DBEAFE',
    badgeText: '#1E40AF',
    symbol: '⬢',
    symbolName: 'Hexagon',
  },
  emerald: {
    id: 'emerald',
    name: 'Forest Jade',
    primary: '#059669',
    shadow: '#064E3B',
    visor: '#D1FAE5',
    badgeBg: '#ECFDF5',
    badgeText: '#065F46',
    symbol: '✿',
    symbolName: 'Clover',
  },
  graphite: {
    id: 'graphite',
    name: 'Slate Carbon',
    primary: '#475569',
    shadow: '#1E293B',
    visor: '#E2E8F0',
    badgeBg: '#F1F5F9',
    badgeText: '#334155',
    symbol: '⬟',
    symbolName: 'Pentagon',
  },
  cream: {
    id: 'cream',
    name: 'Ivory Snow',
    primary: '#E2E8F0',
    shadow: '#94A3B8',
    visor: '#BAE6FD',
    badgeBg: '#F8FAFC',
    badgeText: '#475569',
    symbol: '☾',
    symbolName: 'Crescent',
  },
  tangerine: {
    id: 'tangerine',
    name: 'Tangerine',
    primary: '#FB923C',
    shadow: '#EA580C',
    visor: '#FEF08A',
    badgeBg: '#FFEDD5',
    badgeText: '#9A3412',
    symbol: '◈',
    symbolName: 'Rhombus',
  },
  lilac: {
    id: 'lilac',
    name: 'Soft Plum',
    primary: '#C084FC',
    shadow: '#9333EA',
    visor: '#F3E8FF',
    badgeBg: '#F3E8FF',
    badgeText: '#6B21A8',
    symbol: '🛡',
    symbolName: 'Shield',
  },
};

export const COLOR_LIST: PlayerColorId[] = [
  'coral',
  'mint',
  'sky',
  'butter',
  'lavender',
  'rosewood',
  'cerulean',
  'emerald',
  'graphite',
  'cream',
  'tangerine',
  'lilac',
];

export const MAP_ROOMS: MapRoom[] = [
  {
    id: 'cafeteria',
    name: 'Cafeteria',
    x: 600,
    y: 100,
    width: 400,
    height: 300,
    isEmergency: true,
    tasks: ['DOWNLOAD_DATA', 'WIRES'],
    hasVent: true,
    ventIds: ['vent_cafe'],
  },
  {
    id: 'weapons',
    name: 'Weapons',
    x: 1100,
    y: 120,
    width: 260,
    height: 240,
    tasks: ['ASTEROIDS', 'DOWNLOAD_DATA'],
    hasVent: true,
    ventIds: ['vent_weapons'],
  },
  {
    id: 'o2',
    name: 'O2 Life Support',
    x: 1050,
    y: 420,
    width: 220,
    height: 200,
    tasks: ['SWIPE_CARD'],
    hasVent: false,
  },
  {
    id: 'navigation',
    name: 'Navigation',
    x: 1350,
    y: 440,
    width: 260,
    height: 300,
    tasks: ['DIVERT_POWER', 'DOWNLOAD_DATA'],
    hasVent: true,
    ventIds: ['vent_nav_top', 'vent_nav_bot'],
  },
  {
    id: 'shields',
    name: 'Shields',
    x: 1100,
    y: 780,
    width: 260,
    height: 240,
    tasks: ['CALIBRATE', 'DIVERT_POWER'],
    hasVent: true,
    ventIds: ['vent_shields'],
  },
  {
    id: 'communications',
    name: 'Comms',
    x: 820,
    y: 860,
    width: 220,
    height: 180,
    tasks: ['DOWNLOAD_DATA'],
    hasVent: false,
  },
  {
    id: 'storage',
    name: 'Storage Hub',
    x: 580,
    y: 680,
    width: 380,
    height: 360,
    tasks: ['WIRES'],
    hasVent: false,
  },
  {
    id: 'admin',
    name: 'Admin Station',
    x: 1040,
    y: 650,
    width: 220,
    height: 200,
    isAdmin: true,
    tasks: ['SWIPE_CARD', 'DOWNLOAD_DATA'],
    hasVent: true,
    ventIds: ['vent_admin'],
  },
  {
    id: 'electrical',
    name: 'Electrical',
    x: 320,
    y: 520,
    width: 220,
    height: 260,
    tasks: ['CALIBRATE', 'WIRES', 'DIVERT_POWER'],
    hasVent: true,
    ventIds: ['vent_elec'],
  },
  {
    id: 'lower_engine',
    name: 'Lower Engine',
    x: 80,
    y: 720,
    width: 200,
    height: 240,
    tasks: ['MANIFOLD', 'DIVERT_POWER'],
    hasVent: true,
    ventIds: ['vent_lower_eng'],
  },
  {
    id: 'security',
    name: 'Security Deck',
    x: 300,
    y: 320,
    width: 200,
    height: 180,
    isSecurity: true,
    tasks: ['WIRES'],
    hasVent: true,
    ventIds: ['vent_sec'],
  },
  {
    id: 'reactor',
    name: 'Core Reactor',
    x: 40,
    y: 360,
    width: 220,
    height: 320,
    tasks: ['MANIFOLD', 'CALIBRATE'],
    hasVent: true,
    ventIds: ['vent_reactor_top', 'vent_reactor_bot'],
  },
  {
    id: 'upper_engine',
    name: 'Upper Engine',
    x: 80,
    y: 80,
    width: 200,
    height: 240,
    tasks: ['MANIFOLD', 'DIVERT_POWER'],
    hasVent: true,
    ventIds: ['vent_upper_eng'],
  },
  {
    id: 'medbay',
    name: 'MedBay Lab',
    x: 340,
    y: 100,
    width: 220,
    height: 200,
    tasks: ['MEDBAY_SCAN'],
    hasVent: true,
    ventIds: ['vent_medbay'],
  },
];

export const MAP_CORRIDORS: { x: number; y: number; width: number; height: number }[] = [
  // Cafe to Weapons
  { x: 990, y: 180, width: 120, height: 80 },
  // Weapons to O2 / Nav
  { x: 1200, y: 350, width: 70, height: 100 },
  // O2 to Nav
  { x: 1260, y: 480, width: 100, height: 80 },
  // Nav to Shields
  { x: 1260, y: 700, width: 100, height: 90 },
  // Shields to Comms/Storage
  { x: 950, y: 880, width: 160, height: 80 },
  // Cafe to Storage (Central hallway)
  { x: 740, y: 390, width: 90, height: 300 },
  // Cafe to Admin hallway
  { x: 890, y: 460, width: 160, height: 80 },
  // Admin to Storage
  { x: 950, y: 720, width: 100, height: 80 },
  // Storage to Electrical
  { x: 530, y: 640, width: 60, height: 80 },
  // Storage to Lower Engine
  { x: 270, y: 820, width: 320, height: 80 },
  // Electrical to Security
  { x: 380, y: 490, width: 70, height: 40 },
  // Security to Upper Engine
  { x: 270, y: 260, width: 160, height: 70 },
  // Upper Engine to Reactor
  { x: 140, y: 310, width: 80, height: 60 },
  // Lower Engine to Reactor
  { x: 140, y: 670, width: 80, height: 60 },
  // Cafe to MedBay
  { x: 550, y: 160, width: 60, height: 80 },
  // MedBay to Upper corridor
  { x: 270, y: 150, width: 80, height: 70 },
];

export const MAP_VENTS: MapVent[] = [
  { id: 'vent_cafe', room: 'Cafeteria', x: 940, y: 140, connectedVents: ['vent_admin', 'vent_weapons'] },
  { id: 'vent_weapons', room: 'Weapons', x: 1300, y: 160, connectedVents: ['vent_cafe', 'vent_nav_top'] },
  { id: 'vent_nav_top', room: 'Navigation', x: 1540, y: 480, connectedVents: ['vent_weapons', 'vent_nav_bot', 'vent_shields'] },
  { id: 'vent_nav_bot', room: 'Navigation', x: 1540, y: 700, connectedVents: ['vent_nav_top', 'vent_shields'] },
  { id: 'vent_shields', room: 'Shields', x: 1300, y: 960, connectedVents: ['vent_nav_bot', 'vent_nav_top'] },
  { id: 'vent_admin', room: 'Admin', x: 1210, y: 800, connectedVents: ['vent_cafe'] },
  { id: 'vent_elec', room: 'Electrical', x: 360, y: 560, connectedVents: ['vent_sec', 'vent_medbay'] },
  { id: 'vent_sec', room: 'Security', x: 340, y: 450, connectedVents: ['vent_elec', 'vent_medbay'] },
  { id: 'vent_medbay', room: 'MedBay', x: 380, y: 140, connectedVents: ['vent_elec', 'vent_sec'] },
  { id: 'vent_reactor_top', room: 'Reactor', x: 80, y: 400, connectedVents: ['vent_upper_eng', 'vent_reactor_bot'] },
  { id: 'vent_reactor_bot', room: 'Reactor', x: 80, y: 640, connectedVents: ['vent_lower_eng', 'vent_reactor_top'] },
  { id: 'vent_upper_eng', room: 'Upper Engine', x: 120, y: 120, connectedVents: ['vent_reactor_top'] },
  { id: 'vent_lower_eng', room: 'Lower Engine', x: 120, y: 910, connectedVents: ['vent_reactor_bot'] },
];

export const SECURITY_CAMERAS: SecurityCamera[] = [
  { id: 'cam_hallway_east', name: 'East Corridor (Nav/O2)', x: 1230, y: 420, room: 'Corridor E', fovAngle: 90 },
  { id: 'cam_hallway_west', name: 'West Corridor (Engines)', x: 240, y: 480, room: 'Corridor W', fovAngle: 270 },
  { id: 'cam_hallway_south', name: 'Admin / Storage Crossing', x: 920, y: 650, room: 'Admin Crossroads', fovAngle: 180 },
  { id: 'cam_medbay_hall', name: 'MedBay Access', x: 480, y: 220, room: 'MedBay Corridor', fovAngle: 0 },
];

// Stations where tasks can be interacted with
export interface TaskStation {
  id: string;
  type: TaskType;
  name: string;
  room: string;
  x: number;
  y: number;
  icon: string;
}

export const TASK_STATIONS: TaskStation[] = [
  { id: 'task_wires_cafe', type: 'WIRES', name: 'Fix Wiring (Cafeteria)', room: 'Cafeteria', x: 650, y: 130, icon: 'Zap' },
  { id: 'task_download_cafe', type: 'DOWNLOAD_DATA', name: 'Download Data (Cafeteria)', room: 'Cafeteria', x: 930, y: 350, icon: 'Download' },
  { id: 'task_asteroids_weapons', type: 'ASTEROIDS', name: 'Clear Asteroids (Weapons)', room: 'Weapons', x: 1300, y: 220, icon: 'Crosshair' },
  { id: 'task_download_weapons', type: 'DOWNLOAD_DATA', name: 'Download Data (Weapons)', room: 'Weapons', x: 1140, y: 150, icon: 'Download' },
  { id: 'task_swipe_o2', type: 'SWIPE_CARD', name: 'Clean O2 Filter (Life Support)', room: 'O2 Life Support', x: 1150, y: 460, icon: 'CreditCard' },
  { id: 'task_divert_nav', type: 'DIVERT_POWER', name: 'Divert Power (Navigation)', room: 'Navigation', x: 1470, y: 490, icon: 'Sliders' },
  { id: 'task_download_nav', type: 'DOWNLOAD_DATA', name: 'Download Data (Navigation)', room: 'Navigation', x: 1560, y: 600, icon: 'Download' },
  { id: 'task_calibrate_shields', type: 'CALIBRATE', name: 'Calibrate Distributor (Shields)', room: 'Shields', x: 1220, y: 970, icon: 'Compass' },
  { id: 'task_divert_shields', type: 'DIVERT_POWER', name: 'Divert Power (Shields)', room: 'Shields', x: 1310, y: 830, icon: 'Sliders' },
  { id: 'task_download_comms', type: 'DOWNLOAD_DATA', name: 'Download Data (Comms)', room: 'Comms', x: 920, y: 990, icon: 'Download' },
  { id: 'task_wires_storage', type: 'WIRES', name: 'Fix Wiring (Storage)', room: 'Storage Hub', x: 620, y: 990, icon: 'Zap' },
  { id: 'task_swipe_admin', type: 'SWIPE_CARD', name: 'Swipe Card (Admin)', room: 'Admin Station', x: 1180, y: 690, icon: 'CreditCard' },
  { id: 'task_download_admin', type: 'DOWNLOAD_DATA', name: 'Upload Data (Admin)', room: 'Admin Station', x: 1080, y: 800, icon: 'Upload' },
  { id: 'task_calibrate_elec', type: 'CALIBRATE', name: 'Calibrate Distributor (Electrical)', room: 'Electrical', x: 360, y: 730, icon: 'Compass' },
  { id: 'task_wires_elec', type: 'WIRES', name: 'Fix Wiring (Electrical)', room: 'Electrical', x: 500, y: 560, icon: 'Zap' },
  { id: 'task_divert_elec', type: 'DIVERT_POWER', name: 'Divert Power (Electrical)', room: 'Electrical', x: 440, y: 730, icon: 'Sliders' },
  { id: 'task_manifold_lower', type: 'MANIFOLD', name: 'Unlock Manifolds (Lower Engine)', room: 'Lower Engine', x: 130, y: 840, icon: 'Grid' },
  { id: 'task_divert_lower', type: 'DIVERT_POWER', name: 'Divert Power (Lower Engine)', room: 'Lower Engine', x: 230, y: 760, icon: 'Sliders' },
  { id: 'task_wires_sec', type: 'WIRES', name: 'Fix Wiring (Security)', room: 'Security Deck', x: 440, y: 350, icon: 'Zap' },
  { id: 'task_manifold_reactor', type: 'MANIFOLD', name: 'Unlock Manifolds (Reactor)', room: 'Core Reactor', x: 90, y: 480, icon: 'Grid' },
  { id: 'task_calibrate_reactor', type: 'CALIBRATE', name: 'Calibrate Core (Reactor)', room: 'Core Reactor', x: 90, y: 580, icon: 'Compass' },
  { id: 'task_manifold_upper', type: 'MANIFOLD', name: 'Unlock Manifolds (Upper Engine)', room: 'Upper Engine', x: 130, y: 240, icon: 'Grid' },
  { id: 'task_divert_upper', type: 'DIVERT_POWER', name: 'Divert Power (Upper Engine)', room: 'Upper Engine', x: 230, y: 130, icon: 'Sliders' },
  { id: 'task_medbay_scan', type: 'MEDBAY_SCAN', name: 'Submit Biometric Scan (MedBay)', room: 'MedBay Lab', x: 440, y: 220, icon: 'Activity' },
];

export const EMERGENCY_BUTTON_POS = { x: 800, y: 240 };
export const ADMIN_TABLE_POS = { x: 1140, y: 740 };
export const SECURITY_DESK_POS = { x: 380, y: 390 };
